### PR TITLE
[NEW BLOCK] DAA injection

### PR DESCRIPTION
**Pull request by qiyundai**
This PR introduces a new block called daa-injection
First row of this block adjusts the daa-lh tag of the **next block**
The remaining config rows will adjust the daa-ll tags of links that match the url of each row's key column
The block will remove itself after finishing the job

Resolves: [MWPW-156261](https://jira.corp.adobe.com/browse/MWPW-156261)

Test URLs:
- Before: https://dev--events-milo--adobecom.hlx.page/
- After: https://daa-injection--events-milo--adobecom.hlx.page/

### CODE REVIEW

**Review by apganapa-adobe — APPROVED** [review]

**Review by vgoodric — CHANGES_REQUESTED** [review]
@qiyundai is this redundant with the work you've asked for from our team?  I feel like this approach is alot more authoring effort.
cc: @markpadbe

**Comment by qiyundai** [comment]
> @qiyundai is this redundant with the work you've asked for from our team?  I feel like this approach is alot more authoring effort.
> 
> cc: @markpadbe 

Hi Vivian,

Thanks for taking a look at this. This new block does not aim to overlap with what @markpadbe has worked on. It's made to override inaccurate generated lh & ll tags even with the increased word count. If the 3rd issue we had discussed in that meeting.

For example, you might still remember that we have a couple of text blocks housing some CTAs without contextual headings. Even with the increased word count, these blocks will not have enough relevant segments to help John his analytics dash with simple and clear levels. This block is to help with that by allowing authors designate daa-lh and daa-ll tags of a block without the help of CSS hidden headings / JS adding and removing a heading (both of which are bad for SEO). It also means we don't have to build a duplicate of Milo blocks each time we run into this kind of issues.

It's true that this is purely authoring work but given that we 1. Use template word docs + fragments for our event details page; 2. Can use [[metadata-placeholders]] in these daa-injection blocks too, this really is just a once a while setup effort on limited amount of pages. At the current phase, we only need to add this block in 2 event template fragments and ~10 product blade fragments. The next time we'll need to do this is when we refresh the product blades or release a new event template.

**Comment by vgoodric** [comment]
@qiyundai ty for the explanation.  Based on time constraints, I don't think @markpadbe should try to account for the interactions between this new block and his tickets.  If it turns out the code needs to be adjusted to work with this block, that may have to be a later update.

**Comment by qiyundai** [comment]
> @qiyundai ty for the explanation.  Based on time constraints, I don't think @markpadbe should try to account for the interactions between this new block and his tickets.  If it turns out the code needs to be adjusted to work with this block, that may have to be a later update.

@vgoodric no problem. I'm not anticipating this block to have any side effects on Mark's work. Regarding daa-ll, this block will simply override the default generated daa-ll and become the final verdict. This should be the desired effect by using the block. I don't think we'll be using this for the majority of the daa tags. Rather, just the ones living in blocks without headings or in block-group where the generated CTA daa-ll position index is wrong. It also shouldn't have any juxtaposition over the modal open event changes @markpadbe is working on.

In the unforeseen circumstances that it somehow does conflict with @markpadbe's work, I'm happy to make the necessary changes to resolve any side effects caused by this block.

**Review by apganapa-adobe — APPROVED** [review]

**Pull request merged**
